=== jharner/JavaStat/src/wvustat/launcher/dtd/contents.dtd
<!ELEMENT contents (title, javaStatTool?, node*)>
<!ELEMENT node (title, javaStatTool?, node*)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT javaStatTool (toolName, paramList?)>
<!ELEMENT toolName (#PCDATA)>
<!ELEMENT paramList (param+)>
<!ELEMENT param (name, value)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT value (#PCDATA)>

=== jharner/JavaStat/src/wvustat/launcher/DefaultContent.xml
<?xml version="1.0"?>
<!DOCTYPE contents SYSTEM "http://stat.wvu.edu/myJavaStat/dtd/contents.dtd">

<contents>
  <title>LifeStats</title>
  <javaStatTool>
    <toolName>PDF Viewer</toolName>
    <paramList>
      <param>
        <name>content</name>
        <value>/contents/fm.pdf</value>
      </param>
      <param>
        <name>auth</name>
        <value>false</value>
      </param>
    </paramList>
  </javaStatTool>
  
  <node>
    <title>Glossary</title>
    <javaStatTool>
      <toolName>PDF Viewer</toolName>
      <paramList>
        <param>
          <name>content</name>
          <value>/contents/glossary.pdf</value>
        </param>
        <param>
          <name>auth</name>
          <value>false</value>
        </param>
      </paramList>
    </javaStatTool>
  </node>
  
  <node>
    <title>Part I: Describing Data</title>
    <node>
      <title>Chapter 1 Describing Data</title>
      <javaStatTool>
        <toolName>PDF Viewer</toolName>
        <paramList>
          <param>
            <name>content</name>
            <value>/contents/chap01.pdf</value>
          </param>
          <param>
            <name>auth</name>
            <value>false</value>
          </param>
        </paramList>
      </javaStatTool>
    
      <node>
        <title>Notes</title>
        <javaStatTool>
          <toolName>PDF Viewer</toolName>
          <paramList>
            <param>
              <name>content</name>
              <value>/contents/Stat211Chap1.pdf</value>
            </param>
            <param>
              <name>auth</name>
              <value>false</value>
            </param>
          </paramList>
        </javaStatTool>
      </node>
    
      <node>
        <title>Data</title>
        <javaStatTool>
          <toolName>Data</toolName>
          <paramList>
            <param>
              <name>id</name>
              <value>1</value>
            </param>
          </paramList>
        </javaStatTool>
      </node>

      <node>
        <title>Examples</title>
        <javaStatTool>
          <toolName>Examples</toolName>
          <paramList>
            <param>
              <name>id</name>
              <value>1</value>
            </param>
          </paramList>
        </javaStatTool>
      </node>
    </node>

    <node>
      <title>Chapter 2 Summarizing Data</title>
      <javaStatTool>
        <toolName>PDF Viewer</toolName>
        <paramList>
          <param>
            <name>content</name>
            <value>/contents/chap02.pdf</value>
          </param>
          <param>
            <name>auth</name>
            <value>false</value>
          </param>
        </paramList>
      </javaStatTool>
      
      <node>
        <title>Notes</title>
        <javaStatTool>
          <toolName>PDF Viewer</toolName>
          <paramList>
            <param>
              <name>content</name>
              <value>/contents/Stat211Chap2.pdf</value>
            </param>
            <param>
              <name>auth</name>
              <value>false</value>
            </param>
          </paramList>
        </javaStatTool>
      </node>
      
      <node>
        <title>Data</title>
        <javaStatTool>
          <toolName>Data</toolName>
          <paramList>
            <param>
              <name>id</name>
              <value>2</value>
            </param>
          </paramList>
        </javaStatTool>
      </node>

      <node>
        <title>Examples</title>
        <javaStatTool>
          <toolName>Examples</toolName>
          <paramList>
            <param>
              <name>id</name>
              <value>2</value>
            </param>
          </paramList>
        </javaStatTool>
      </node>
    </node>

    <node>
      <title>Chapter 3 Linear Relationships</title>
      <javaStatTool>
        <toolName>PDF Viewer</toolName>
        <paramList>
          <param>
            <name>content</name>
            <value>/contents/chap03.pdf</value>
          </param>
          <param>
            <name>auth</name>
            <value>true</value>
          </param>
        </paramList>
      </javaStatTool>
      
      <node>
        <title>Notes</title>
        <javaStatTool>
          <toolName>PDF Viewer</toolName>
          <paramList>
            <param>
              <name>content</name>
              <value>/contents/Stat211Chap3.pdf</value>
            </param>
            <param>
              <name>auth</name>
              <value>false</value>
            </param>
          </paramList>
        </javaStatTool>
      </node>

      <node>
        <title>Data</title>
        <javaStatTool>
          <toolName>Data</toolName>
          <paramList>
            <param>
              <name>id</name>
              <value>3</value>
            </param>
          </paramList>
        </javaStatTool>
      </node>

      <node>
        <title>Correlation</title>
        <javaStatTool>
          <toolName>
            Correlation Coefficient Test
          </toolName>
        </javaStatTool>
      </node>
<!--
      <node>
        <title>Grapher</title>
        <javaStatTool>
          <toolName>Grapher</toolName>
        </javaStatTool>
      </node>
-->
      <node>
        <title>Examples</title>
        <javaStatTool>
          <toolName>Examples</toolName>
          <paramList>
            <param>
              <name>id</name>
              <value>3</value>
            </param>
          </paramList>
        </javaStatTool>
      </node>
    </node>
  </node>

  <node>
    <title>Part II Probability Modeling</title>

    <node>
      <title>
        Chapter 4 Probabilities &amp; Simulation
      </title>
      
      <javaStatTool>
        <toolName>PDF Viewer</toolName>
        <paramList>
          <param>
            <name>content</name>
            <value>/contents/chap04.pdf</value>
          </param>
          <param>
            <name>auth</name>
            <value>true</value>
          </param>
        </paramList>
      </javaStatTool>
      
      <node>
        <title>Notes</title>
        <javaStatTool>
          <toolName>PDF Viewer</toolName>
          <paramList>
            <param>
              <name>content</name>
              <value>/contents/Stat211Chap4.pdf</value>
            </param>
            <param>
              <name>auth</name>
              <value>false</value>
            </param>
          </paramList>
        </javaStatTool>
      </node>
      
      <node>
        <title>Probability Definition</title>
        <javaStatTool>
          <toolName>
            Relative Frequency
          </toolName>
        </javaStatTool>
      </node>
      <node>
        <title>Box Model</title>

        <javaStatTool>
          <toolName>
            Box Model
          </toolName>
        </javaStatTool>
      </node>

      <node>
        <title>Five-step Method</title>

        <javaStatTool>
          <toolName>
            Five Step
          </toolName>
        </javaStatTool>
      </node>

      <node>
        <title>Poker</title>

        <javaStatTool>
          <toolName>
            Poker
          </toolName>
        </javaStatTool>
      </node>

      <node>
        <title>Examples</title>
        <javaStatTool>
          <toolName>Examples</toolName>
          <paramList>
            <param>
              <name>id</name>
              <value>4</value>
            </param>
          </paramList>
        </javaStatTool>
      </node>
    </node>

    <node>
      <title>Chapter 5 Expected Value &amp; Simulation</title>
      
      <javaStatTool>
        <toolName>PDF Viewer</toolName>
        <paramList>
          <param>
            <name>content</name>
            <value>/contents/chap05.pdf</value>
          </param>
          <param>
            <name>auth</name>
            <value>true</value>
          </param>
        </paramList>
      </javaStatTool>
      
      <node>
        <title>Notes</title>
        <javaStatTool>
          <toolName>PDF Viewer</toolName>
          <paramList>
            <param>
              <name>content</name>
              <value>/contents/Stat211Chap5.pdf</value>
            </param>
            <param>
              <name>auth</name>
              <value>false</value>
            </param>
          </paramList>
        </javaStatTool>
      </node>

      <node>
        <title>Five-step Method</title>

        <javaStatTool>
          <toolName>
            Five Step
          </toolName>
        </javaStatTool>
      </node>
    </node>

    <node>
      <title>Chapter 6 Probability Distributions</title>
      
      <javaStatTool>
        <toolName>PDF Viewer</toolName>
        <paramList>
          <param>
            <name>content</name>
            <value>/contents/chap06.pdf</value>
          </param>
          <param>
            <name>auth</name>
            <value>true</value>
          </param>
        </paramList>
      </javaStatTool>
      
      <node>
        <title>Notes</title>
        <javaStatTool>
          <toolName>PDF Viewer</toolName>
          <paramList>
            <param>
              <name>content</name>
              <value>/contents/Stat211Chap6.pdf</value>
            </param>
            <param>
              <name>auth</name>
              <value>false</value>
            </param>
          </paramList>
        </javaStatTool>
      </node>
      
      <node>
        <title>Binomial Distribution</title>
        <javaStatTool>
          <toolName>Discrete Distribution</toolName>
          <paramList>
            <param>
              <name>DistributionName</name>
              <value>Binomial</value>
            </param>
            <param>
              <name>n</name>
              <value>40</value>
            </param>
            <param>
              <name>p</name>
              <value>0.5</value>
            </param>
          </paramList>
        </javaStatTool>
      </node>
      <node>
        <title>Poisson Distribution</title>
